#!/bin/bash

if [ -f .env ]; then
  export $(cat .env | sed 's/#.*//g' | xargs)
fi

# include base docker compose file
COMPOSE_FILES="-f docker-compose.yml"

for i in $(seq 1 ${#PORTAL_MODULES}); do
  # accounts module - alias "a"
  if [ ${PORTAL_MODULES:i-1:1} == "a" ]; then
    COMPOSE_FILES+=" -f docker-compose.accounts.yml"
  fi

  # jaeger module - alias "j"
  if [ ${PORTAL_MODULES:i-1:1} == "j" ]; then
    COMPOSE_FILES+=" -f docker-compose.jaeger.yml"
  fi
done

# override file if exists
if [ -f docker-compose.override.yml ]; then
  COMPOSE_FILES+=" -f docker-compose.override.yml"
fi

docker-compose $COMPOSE_FILES $@
