#!/bin/bash

if [ -f .env ]; then
  OLD_IFS=$IFS; IFS=$'\n'; for x in `grep -v '^#.*' .env`; do export $x; done; IFS=$OLD_IFS
fi

# include base docker compose file
COMPOSE_FILES="-f docker-compose.yml"

for i in $(seq 1 ${#PORTAL_MODULES}); do
  # accounts module - alias "a"
  if [[ ${PORTAL_MODULES:i-1:1} == "a" ]]; then
    COMPOSE_FILES+=" -f docker-compose.mongodb.yml -f docker-compose.accounts.yml"
  fi

  # blocker module - alias "b"
  if [[ ${PORTAL_MODULES:i-1:1} == "b" ]]; then
    COMPOSE_FILES+=" -f docker-compose.blocker.yml"
  fi

  # jaeger module - alias "j"
  if [[ ${PORTAL_MODULES:i-1:1} == "j" ]]; then
    COMPOSE_FILES+=" -f docker-compose.jaeger.yml"
  fi

  # mongodb module - alias "m". implied by "a" or "u"
  if [[ ${PORTAL_MODULES:i-1:1} == "m" ]]; then
    COMPOSE_FILES+=" -f docker-compose.mongodb.yml"
  fi

  # abuse module - alias "u"
  if [[ ${PORTAL_MODULES:i-1:1} == "u" ]]; then
    COMPOSE_FILES+=" -f docker-compose.mongodb.yml -f docker-compose.blocker.yml -f docker-compose.abuse.yml"
  fi
done

# override file if exists
if [[ -f docker-compose.override.yml ]]; then
  COMPOSE_FILES+=" -f docker-compose.override.yml"
fi

docker-compose $COMPOSE_FILES $@
