[[redirects]]
    from = "/skynet/skyfile"
    to = "https://siasky.net/skynet/skyfile"
    status = 200
    force = true

[[redirects]]
    from = "/file/*"
    to = "https://siasky.net/file/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/"
    to = "/"
    status = 200

[[redirects]]
    from = "/*"
    to = "https://siasky.net/:splat"
    status = 200