# Define action name, description, and inputs
name: "Python Black Lint"
description: "Lint python code with black"

# Define action steps
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
        architecture: x64

    - run: |
        pip install black
        black --check .
      shell: bash
