name: Deploy webapp to Skynet

on:
  pull_request:
    paths:
      - "packages/webapp/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn

      - name: "Build webapp"
        run: yarn workspace webapp build
        env:
          GATSBY_API_URL: "https://siasky.net"

      - name: "Deploy to Skynet"
        uses: kwypchlo/deploy-to-skynet-action@main
        with:
          upload-dir: packages/webapp/public
          github-token: ${{ secrets.GITHUB_TOKEN }}
